version: "3.8"
services:
  flask:
    build:
      context: flask_docker
      dockerfile: Dockerfile 
    logging: 
      driver: json-file 
    volumes:
            - ./flask_docker/docker_code/:/var/www
    environment:
      APP_ENV: "development"
      FLASK_ENV: "development" # Setting to "development" enables Flask debugger.
      APP_DEBUG: "true"
      APP_PORT: 5001
      DB_URL: "mongodb://admin:secret@127.0.0.1:27017/xmapdb"
    ports:
      - 5001:5001
    entrypoint:
      ["flask", "run", "-p", "5001", "-h", "0.0.0.0", "--debugger"]
    restart: "no"
  mongodb:
    image: mongo:latest
    container_name: 'xmap-local-mongo-container'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - ~/data/mongo/db:/data/db
      - ~/data/mongo/log:/var/log/mongodb
    ports:
      - 27017:27017
networks:
    app:
        driver: bridge