version: "3.8"
services:
  flask:
    build:
      context: flask_docker
      dockerfile: Dockerfile 
    logging: 
      driver: json-file 
    volumes:
            - ./flask_docker/docker_code/:/var/www
    environment:
      APP_ENV: "development"
      FLASK_ENV: "development" # Setting to "development" enables Flask debugger.
      APP_DEBUG: "true"
      APP_PORT: 5001
      # DB_URL: "mongodb+srv://admin:xmap-secret@cluster0.wddj4.mongodb.net/xmapdb?retryWrites=true&w=majority"
      DB_URL: "mongodb://mongodb:27017/xmapdb"
      # Set up email server
      MAIL_SERVER: 'smtp.gmail.com'
      MAIL_PORT: 465
      EMAIL_USER: "xmap.developer@gmail.com"
      EMAIL_PASSWORD: "xmap-secret"
      SECRET: "xmap-secret" #testing only - don't use in production!
    ports:
      - 5001:5001
    entrypoint:
      ["flask", "run", "-p", "5001", "-h", "0.0.0.0", "--debugger"]
    restart: "no"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    volumes:
      - ~/data/mongo/db:/data/db
      - ~/data/mongo/log:/var/log/mongodb
    ports:
      - 27017:27017
    restart: always

networks: 
  default:
    name: flask